app/user/views.py
from app.user.forms import LoginForm, RegisterForm
from app.user.models import User
from app.user.utils import create_user

from flask import Blueprint, flash, redirect, render_template, url_for

from flask_login import current_user, login_user, logout_user

blueprint = Blueprint("user", __name__, url_prefix="/user")


@blueprint.route("/register")
def register_page():
    if current_user.is_authenticated:
        return redirect(url_for("index_page"))
    title = "Регистрация"
    form = RegisterForm()
    return render_template("user/register.html", page_title=title, form=form)


@blueprint.route("/process_register", methods=["POST"])
def process_register():
    form = RegisterForm()

    if form.validate_on_submit():
        create_user(form)
        flash("Вы успешно зарегистрировались :)")
        return redirect(url_for("user.login_page"))

    flash("Исправте ошибки в форме регистрации!")
    return redirect(url_for("user.register_page"))


@blueprint.route("/login")
def login_page():
    if current_user.is_authenticated:
        return redirect(url_for("index_page"))
    title = "Авторизация"
    form = LoginForm()
    return render_template("user/login.html", page_title=title, form=form)


@blueprint.route("/process_login", methods=["POST"])
def process_login():
    form = LoginForm()

    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and user.check_password(form.password.data):
            login_user(user, remember=form.remember_user.data)
            flash("Авторизация успешно пройдена")
            return redirect(url_for("index_page"))

    flash("Неправильный email или пароль!")
    return redirect(url_for("user.login_page"))


@blueprint.route("/logout")
def logout():
    logout_user()
    flash("Вы успешно вышли")
    return redirect(url_for("index_page"))


@blueprint.route("/")
def user_page():
    return "Users page"

templates/base.html
<!DOCTYPE html>
<html lang="ru">
<head>

    <link rel="stylesheet" href="{{ url_for('static', filename='css/style.css') }}">
    <link rel="shortcut icon" href="{{ url_for('static', filename='favicon.ico') }}">

     <!-- Required meta tags -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO" crossorigin="anonymous">
    <link rel="stylesheet" href="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/atom-one-dark.min.css">
    <script src="//cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/highlight.min.js"></script>

    <title>{{title}}</title>
</head>
<body>
    {% include 'menu.html' %}

    {% include 'messages.html' %}

    <div class="container">
        <h1>{{ page_title }}</h1>

        <div class="row">
            <div class="col-8">
                {% block content %}{% endblock %}
            </div>

            <div class="col-4">
                {% block content_other %}{% endblock %}
            </div>
        </div>
    </div>

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/js/bootstrap.min.js" integrity="sha384-ChfqqxuZUCnJSK3+MXmPNIyE6ZbWh2IMqE241rYiqJxyMiZ6OW/JmZQ5stwEULTy" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <p>Hello World!</p>

{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block content %}



    <form action="{{ url_for('home.process_login') }}" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>{{ form.email() }}
        </p>
        <p>
            {{ form.password.label }}<br>{{ form.password() }}
        </p>
        <div class="form-group form-check">
            {{ form.remember_user }}
            {{ form.remember_user.label() }}
        </div>
        <p>{{ form.submit }}</p>
    </form>

{% endblock %}

templates/menu.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{{ url_for('index_page') }}">Главная</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
                <a class="nav-link" href="#">Статьи</a>
            </li>
        </ul>
        <form class="form-inline my-2 my-lg-0">
            <input class="form-control mr-sm-2" type="search" placeholder="Где печеньки?" aria-label="Search">
            <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Поиск</button>
        </form>
        <ul class="navbar-nav">
            {% if current_user.is_authenticated %}
                <li class="nav-item">
                    <span class="nav-link">Привет, {{ current_user.first_name }}!</span>
                </li>
                {% if current_user.is_admin %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('admin.admin_page') }}">Админка</a>
                </li>
                {% endif %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.logout') }}">Выйти</a>
                </li>
            {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.register_page') }}">Регистрация</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for('user.login_page') }}">Войти</a>
                </li>
            {% endif %}
        </ul>
    </div>
</nav>

templates/messages.html
{% with messages = get_flashed_messages() %}
        {% if messages %}
            <div class="alert alert-warning" role="alert">
                {% for message in messages %}
                    {{ message }}<br>
                {% endfor %}
            </div>
        {% endif %}
{% endwith %}

templates/register.html
{% extends "base.html" %}
{% block content %}



    <form action="{{ url_for('home.process_register') }}" method="POST">
        {{ form.hidden_tag() }}
        <p>
            {{ form.email.label }}<br>{{ form.email() }}
        </p>
        <p>
            {{ form.password.label }}<br>{{ form.password() }}
        </p>
        <p>
            {{ form.password2.label }}<br>{{ form.password2() }}
        </p>
                <p>
            {{ form.first_name.label }}<br>{{ form.first_name() }}
        </p>
                <p>
            {{ form.middle_name.label }}<br>{{ form.middle_name() }}
        </p>
                <p>
            {{ form.last_name.label }}<br>{{ form.last_name() }}
        </p>
        <p>{{ form.submit }}</p>
    </form>

{% endblock %}